// flow-typed signature: 125b5f5731e00641a41795b76391af0d
// flow-typed version: <<STUB>>/cuid_v^2.1.4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cuid/lib/fingerprint.browser' {
  declare module.exports: any;
}

declare module 'cuid/lib/fingerprint' {
  declare module.exports: any;
}

declare module 'cuid/lib/fingerprint.react-native' {
  declare module.exports: any;
}

declare module 'cuid/lib/pad' {
  declare module.exports: any;
}

declare module 'cuid/test/browser' {
  declare module.exports: any;
}

declare module 'cuid/test/server' {
  declare module.exports: any;
}

declare module 'cuid/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cuid/index' {
  declare module.exports: $Exports<'cuid'>;
}
declare module 'cuid/index.js' {
  declare module.exports: $Exports<'cuid'>;
}
declare module 'cuid/lib/fingerprint.browser.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint.browser'>;
}
declare module 'cuid/lib/fingerprint.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint'>;
}
declare module 'cuid/lib/fingerprint.react-native.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint.react-native'>;
}
declare module 'cuid/lib/pad.js' {
  declare module.exports: $Exports<'cuid/lib/pad'>;
}
declare module 'cuid/test/browser.js' {
  declare module.exports: $Exports<'cuid/test/browser'>;
}
declare module 'cuid/test/server.js' {
  declare module.exports: $Exports<'cuid/test/server'>;
}
declare module 'cuid/test/test.js' {
  declare module.exports: $Exports<'cuid/test/test'>;
}
