// flow-typed signature: 485321244b73d0b50728a06c0e85f8cb
// flow-typed version: <<STUB>>/cuid_v^2.1.6/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cuid/dist/cuid' {
  declare module.exports: any;
}

declare module 'cuid/dist/cuid.min' {
  declare module.exports: any;
}

declare module 'cuid/lib/fingerprint.browser' {
  declare module.exports: any;
}

declare module 'cuid/lib/fingerprint' {
  declare module.exports: any;
}

declare module 'cuid/lib/fingerprint.react-native' {
  declare module.exports: any;
}

declare module 'cuid/lib/getRandomValue.browser' {
  declare module.exports: any;
}

declare module 'cuid/lib/getRandomValue' {
  declare module.exports: any;
}

declare module 'cuid/lib/getRandomValue.react-native' {
  declare module.exports: any;
}

declare module 'cuid/lib/pad' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cuid/dist/cuid.js' {
  declare module.exports: $Exports<'cuid/dist/cuid'>;
}
declare module 'cuid/dist/cuid.min.js' {
  declare module.exports: $Exports<'cuid/dist/cuid.min'>;
}
declare module 'cuid/index' {
  declare module.exports: $Exports<'cuid'>;
}
declare module 'cuid/index.js' {
  declare module.exports: $Exports<'cuid'>;
}
declare module 'cuid/lib/fingerprint.browser.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint.browser'>;
}
declare module 'cuid/lib/fingerprint.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint'>;
}
declare module 'cuid/lib/fingerprint.react-native.js' {
  declare module.exports: $Exports<'cuid/lib/fingerprint.react-native'>;
}
declare module 'cuid/lib/getRandomValue.browser.js' {
  declare module.exports: $Exports<'cuid/lib/getRandomValue.browser'>;
}
declare module 'cuid/lib/getRandomValue.js' {
  declare module.exports: $Exports<'cuid/lib/getRandomValue'>;
}
declare module 'cuid/lib/getRandomValue.react-native.js' {
  declare module.exports: $Exports<'cuid/lib/getRandomValue.react-native'>;
}
declare module 'cuid/lib/pad.js' {
  declare module.exports: $Exports<'cuid/lib/pad'>;
}
